version: '3.4'

networks:
  weather-dev:
    driver: bridge 

services:
  vuefrontend:
    depends_on:
      - "dotnetapi"
    build:
      context: ./weather-fe
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - weather-dev

  dotnetapi:
    image: dotnetapi:latest
    depends_on:
      - "postgres_image"
    build:
      context: ./weather-be/weather-be
      dockerfile: Dockerfile
    ports:
      - "5055:80"     
    environment:
      DB_CONNECTION_STRING: "Host=postgres_image;Database=weather;Username=postgres;Password=123"
    networks:
      - weather-dev
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "weather"
    networks:
      - weather-dev
volumes:
  db_volume: